name: deseq2
source:
  type: parquet
  path: data.parquet
description: gene expression data from DESeq2 analysis
columns:
- name: gene_name
  type: string
  description: name of the differentially expressed gene
- name: baseMean
  type: float
  description: mean of normalized counts for all samples
- name: log2FoldChange
  type: float
  description: log2 fold change between two conditions
- name: pvalue
  type: float
  description: standard error of the log2 fold change
- name: padj
  type: float
  description: adjusted p-value for multiple testing
- name: Significance
  type: string
  description: direction of differential expression
- name: Geneid
  type: string
  description: Ensembl gene ID
- name: Chr
  type: string
  description: chromosome
- name: start_pos
  type: integer
  description: start position
- name: end_pos
  type: integer
  description: end position
- name: Strand
  type: string
  description: strand orientation
- name: Length
  type: integer
  description: gene length
